services:
  duckdb:
    image: ghcr.io/duckdb/duckdb:latest
    container_name: duckdb
    command: ["tail", "-f", "/dev/null"]  # keep container running
    env_file:
      - .env
    volumes:
      - ./data:/data
    working_dir: /data
    restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8080:8978"
    env_file:
      - .env
    environment:
      - CB_SERVER_PORT=8978
      - CB_ADMIN_NAME=${DUCKDB_USER}
      - CB_ADMIN_PASSWORD=${DUCKDB_PASSWORD}
    volumes:
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
      - ./data:/data
    restart: unless-stopped