services:
  ntopng:
    image: ntop/ntopng:latest
    container_name: ntopng
    network_mode: host
    volumes:
      - ./ntopng.license:/etc/ntopng.license:ro
      - ./data:/var/lib/ntopng
    command: ["-i", "eth0", "--data-dir", "/var/lib/ntopng"]
    restart: unless-stopped