services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:18.7.2
    container_name: teleport
    hostname: localhost
    ports:
      - "3025:3025"   # Auth service
      - "3080:3080"   # Web UI
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
    command: start --config=/etc/teleport/teleport.yaml
    restart: unless-stopped